### ISSUE TITLE
ocr.h lacks "#include "resultiterator.h" and alpr segfault 

### ISSUE THREAD

**Issue by Silex** [openalpr/openalpr#1]
Hello,

To compile on ubuntu 12.04, I had to add `#include "resultiterator.h"` in ocr.h:

```
/home/philippe/work/openalpr/src/openalpr/ocr.cpp: In member function ‘void OCR::performOCR(std::vector<cv::Mat>, std::vector<cv::Rect_<int> >)’:
/home/philippe/work/openalpr/src/openalpr/ocr.cpp:84:32: error: invalid use of incomplete type ‘struct tesseract::ResultIterator’
/usr/include/tesseract/baseapi.h:83:7: error: forward declaration of ‘struct tesseract::ResultIterator’
```

And then the binary segfaulted in ocr.cpp around line 100;

``` c++
const char* choice = ci.GetUTF8Text();
postProcessor->addLetter(*choice, j, ci.Confidence());
```

It segfault because choice is value 0x0. If I comment the whole "post-process" block then it still work and gives decent results.

I did install opencv manually and for tesseract I did "apt-get install libtesseract-dev", which is version `3.02.01-2`.

Any idea about why I get the segfault?
