### ISSUE TITLE
Compile on Ubuntu 16.04 LTS, requires TIFF4 but only TIFF5 is there

### ISSUE THREAD

**Issue by AbdallahNasir** [openalpr/openalpr#628]
I am trying to compile OpenALPR on Ubuntu 16.04 LTS, 64 bit.  

```
[ 54%] Linking CXX executable alprd
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblept.so: undefined reference to `TIFFReadDirectory@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblept.so: undefined reference to `TIFFGetFieldDefaulted@LIBTIFF_4.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/liblept.so: undefined reference to `TIFFCleanup@LIBTIFF_4.0'
...
```
I tried to install tiff4, but the following error came

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libtiff4-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libtiff5-dev:i386 libtiff5-dev

E: Package 'libtiff4-dev' has no installation candidate
```

I installed tiff5, both 32 and 64 bit, but the same issue happened.

Please advise,
Thanks

**Comment by AbdallahNasir** [comment]
Hello @alucard079 . 
I did not actually. I did a workaround to avoid compiling the library.

Best luck in your work dear

**Comment by alucard079** [comment]
Do I need to compile using the harder way. If I'm going to train ocr with a new country knowing it's different repo?

**Comment by alucard079** [comment]
@AbdallahNasir Do I need to compile using the harder way. If I'm going to train ocr with a new country knowing it's different repo?

**Comment by AbdallahNasir** [comment]
Sorry @alucard079 , I do not know.

**Comment by alucard079** [comment]
have you tried in training ocr of openalpr? @AbdallahNasir

**Comment by JACKHAHA363** [comment]
Also encountering this problem
