### ISSUE TITLE
Problems getting the Python API to work

### ISSUE THREAD

**Issue by Luminaii** [openalpr/openalpr#414]
I am trying to get the Python API to work. I'm running Python 3.5.2.

First issue I came across is that in the openalpr 2.3.0 compiled files for windows, there are files missing to install the python module using setup.py install. I have copied the needed files out of the 2.2.0 version and got it to install. Next problem is that when I'm trying to use the API in python it won't load the class 'Alpr' giving the following error: 
`Traceback (most recent call last):
  File "E:/Projects/Project-PROG-CSN/main.py", line 1, in <module>
    from openalpr import Alpr
  File "C:\Users\Luminai\AppData\Local\Programs\Python\Python35-32\lib\site-packages\openalpr\__init__.py", line 1, in <module>
    from openalpr import Alpr
ImportError: cannot import name 'Alpr'`

I'm not sure if this is due to using the 2.2.0 files as, as far as I know 2.2.0 doesn't support Python 3. However the complied files seem to be missing the python files required for an installation.

I hope I'm a bit clear and this can be solved. I would love to use this software.

Kind Regards

**Comment by matthill** [comment]
It sounds like the python package is not installed properly.  You could use the openalpr Python lib in your code directory and import from there.  Otherwise, I would check the install location (C:\Users\~\AppData\Local\Programs\Python\Python35-32\lib\sitpackages\openalpr\) to see what is in there.

**Comment by Luminaii** [comment]
I ran install.py in the 2.3.0 pre-build files. But the module file is not in there.

**Comment by fmaupas** [comment]
Any update ? I have the same issue

**Comment by Luminaii** [comment]
I ended up using the cloud API. This worked fine for us.

**Comment by fmaupas** [comment]
I realized the issue was that I didn't install the Python bindings after installing the library itself.

You should go to : PATH/TO/LIBRARY/src/bindings/python 

Hope it helps the next one :)

Florian

And then install using : python setup.py install

**Comment by Luminaii** [comment]
I noticed that too, but couldn't find the proper bindings. Great it worked for you :)

**Comment by diogorjs** [comment]
I got the same issue. Was anyone able to install this and run with python? I followed the following steps:

1. Download the openalpr-master from Git (downloaded the zip file)

2. From command line went to **C:\Python35-32\openalpr-master\src\bindings\python** and then ran **python setyp.py install** and got below result

```
C:\Python35-32\openalpr-master\src\bindings\python>python setup.py install
running install
running build
running build_py
running install_lib
running install_egg_info
Removing C:\Python35-32\Lib\site-packages\openalpr-1.0-py3.5.egg-info
Writing C:\Python35-32\Lib\site-packages\openalpr-1.0-py3.5.egg-info
```

3. Checked C:\Python35-32\Lib\site-packages\openalpr and see the following files there:

__pycache__ (Folder)
__init__.py
openalpr.py

4. Then using idle I ran **from openalpr import Alpr** which went fine

5. Then I ran **alpr = Alpr("us", "C:\Python35-32\openalpr-master\config\openalpr.conf", "C:\Python35-32\openalpr-master\runtime_data")** which failed with the following error:

```
Traceback (most recent call last):
  File "C:\Python35-32\lib\site-packages\openalpr\openalpr.py", line 48, in __init__
    self._openalprpy_lib = ctypes.cdll.LoadLibrary("libopenalprpy.dll")
  File "C:\Python35-32\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python35-32\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Não foi possível encontrar o módulo especificado

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    alpr = Alpr("us", "C:\Python35-32\openalpr-master\config\openalpr.conf", "C:\Python35-32\openalpr-master\runtime_data")
  File "C:\Python35-32\lib\site-packages\openalpr\openalpr.py", line 58, in __init__
    raise nex
OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
```

In this folder **C:\Python35-32\openalpr-master\config\** we have the file **openalpr.conf** copied from **openalpr.conf.defaults**

In this folder **C:\Python35-32\openalpr-master\** we have **runtime_data**

And the **openalpr-master(( is in **C:\Python35-32\**

Can someone please help?

Cheers

**Comment by fmaupas** [comment]
Which version did you use ? The pre-compile version ? 

Please read the How To install : https://github.com/peters/openalpr-windows

**Comment by robrant** [comment]
I couldn't find the `setup.py` file either. I successfully installed on OSX Sierra using homebrew. 
```
$ cd /usr/local/Cellar/openalpr/
$ cd HEAD-d317cb9/                    # Just to show which version I'm using.
$ find . -name "setup*"
Nothing.
```
Did the `setup.py` get removed?

**Comment by robrant** [comment]
Me ^ again... this seems like a weird way to fix it, but I now have openalpr installed via homebrew on OSX Sierra _with_ the python bindings. Here's how:

1. Change into the directory into which openalpr was installed (you might actually be able to do this from any directory, but I'm just telling you what definitely works).
```
$> cd /usr/local/Cellar/openalpr
```

2. Clone down the repo from github (you'll need to install git obvs.)
```
$> git clone https://github.com/openalpr/openalpr.git
```

3. Change into the relevant python bindings folder
```
$> cd openalpr/src/bindings/python/
```

4. Run the `setup.py` command
```
$> python setup.py install
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/openalpr
copying openalpr/__init__.py -> build/lib/openalpr
copying openalpr/openalpr.py -> build/lib/openalpr
running install_lib
creating /usr/local/lib/python2.7/site-packages/openalpr
copying build/lib/openalpr/__init__.py -> /usr/local/lib/python2.7/site-packages/openalpr
copying build/lib/openalpr/openalpr.py -> /usr/local/lib/python2.7/site-packages/openalpr
byte-compiling /usr/local/lib/python2.7/site-packages/openalpr/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/openalpr/openalpr.py to openalpr.pyc
running install_egg_info
Writing /usr/local/lib/python2.7/site-packages/openalpr-1.0-py2.7.egg-info
```

5. Test it
```
$> python
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import openalpr
>>> 
```

I haven't tested it beyond that i'm afraid, so it might still fall over later, but it at least gets over the `import` issue I was having. Interested to hear whether it works for others.

**Comment by lmiguelmh** [comment]
Well this is how I got OpenALPR to work on Windows 7/Anaconda 3/python 3.5 x64 :

0. You should uninstall any previous version of ALPR

1. Download the _binaries_ **and** the _source code_ from https://github.com/openalpr/openalpr/releases

2. Unzip the _binaries_ **and** the _source code_ in some directory, for example `C:\OpenALPR`

3. Add the directory where alpr is located to your PATH. In my case `C:\OpenALPR\openalpr_64`

4. Use Anaconda Prompt to install the Python bindings (they are in the source code directory). In my case:

```
cd C:\OpenALPR\openalpr-2.3.0\src\bindings\python
python setup.py install --record files.txt
```

5. Test your installation in the same prompt:

```
cd C:\OpenALPR\openalpr_64
python_test.bat
```

Output:
```
Using OpenALPR 2.3.0
Image size: 497x372
Processing Time: 22.618999
Plate #1
          Plate   Confidence
  -       THECAR   92.207481
  -       THEGAR   81.348961
  -        HECAR   80.229317
  -       TMECAR   78.159492
  -       THE0AR   77.702461
  -       THECAB   77.389000
  -        THEAR   76.510017
```

Now there is a problem with the unload method of the DLL, but that is another issue: `Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x0000000002C04198>>`. BTW this problem only happen when using alpr.unload().

**Comment by lichenguang302** [comment]
@diogorjs i got the same issue, do you have fixed it? Mine as below:
 
>>> alpr = Alpr("us", "D:\openalpr-2.3.0\config\openalpr.conf", "D:\openalpr-2.3
.0\runtime_data")

Exception AttributeError: "Alpr instance has no attribute '_is_loaded_func'" in
<bound method Alpr.__del__ of <openalpr.openalpr.Alpr instance at 0x00000000027B
9148>> ignored
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "openalpr\openalpr.py", line 58, in __init__
    raise nex
OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR i
s properly installed on your system and that the libraries are in the appropriat
e paths.

**Comment by miti0** [comment]
+1

**Comment by nicopereira** [comment]
I had the same problem, just be sure your python version is the correct architecture x86 or x64 same as openalpr.
I solved it installing x64 python

**Comment by vijjubadshah** [comment]
On windows 10
I m using python3.6 with annaconda 64bit every time I run code with openalpr sometimes I get output and sometimes show error and stopped "python stopped working" any solution?


![capture](https://user-images.githubusercontent.com/35923659/37202719-4aa2f22a-23b1-11e8-98f9-8ad95d42608f.JPG)

**Comment by aiteerzhao** [comment]
It may be a problem with your Python compiler. You can go to Stack Overflow to look for a better answer.

At 2018-03-09 18:21:55, "vijjubadshah" <notifications@github.com> wrote:


On windows 10
I m using python3.6 with annaconda 64bit every time I run code with openalpr sometimes I get output and sometimes show error and stopped "python stopped working" any solution?

**Comment by tensor-flower** [comment]
I want to use openalpr python bindings in my virtual environment but cannot locate openalpr library. Outside virtual environment is fine.

**Comment by sai-krishna-msk** [comment]
> Well this is how I got OpenALPR to work on Windows 7/Anaconda 3/python 3.5 x64 :
> 
> 1. You should uninstall any previous version of ALPR
> 2. Download the _binaries_ **and** the _source code_ from https://github.com/openalpr/openalpr/releases
> 3. Unzip the _binaries_ **and** the _source code_ in some directory, for example `C:\OpenALPR`
> 4. Add the directory where alpr is located to your PATH. In my case `C:\OpenALPR\openalpr_64`
> 5. Use Anaconda Prompt to install the Python bindings (they are in the source code directory). In my case:
> 
> ```
> cd C:\OpenALPR\openalpr-2.3.0\src\bindings\python
> python setup.py install --record files.txt
> ```
> 1. Test your installation in the same prompt:
> 
> ```
> cd C:\OpenALPR\openalpr_64
> python_test.bat
> ```
> Output:
> 
> ```
> Using OpenALPR 2.3.0
> Image size: 497x372
> Processing Time: 22.618999
> Plate #1
>           Plate   Confidence
>   -       THECAR   92.207481
>   -       THEGAR   81.348961
>   -        HECAR   80.229317
>   -       TMECAR   78.159492
>   -       THE0AR   77.702461
>   -       THECAB   77.389000
>   -        THEAR   76.510017
> ```
> Now there is a problem with the unload method of the DLL, but that is another issue: `Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x0000000002C04198>>`. BTW this problem only happen when using alpr.unload().

I did not understand the third point could you kindly elaborate, 
Thank you

**Comment by babrubhan** [comment]
Try giving full path of the libopenalprpy.so library file. This issue seems like the python wrapper is not compiled and installed for python3.

Install python3-dev package, and then compile and install openalpr.

For uinstalling the locally compiled version you can use the following command

cd build
sudo make uninstal

**Comment by dhrumin75** [comment]
> Well this is how I got OpenALPR to work on Windows 7/Anaconda 3/python 3.5 x64 :
> 
> 1. You should uninstall any previous version of ALPR
> 2. Download the _binaries_ **and** the _source code_ from https://github.com/openalpr/openalpr/releases
> 3. Unzip the _binaries_ **and** the _source code_ in some directory, for example `C:\OpenALPR`
> 4. Add the directory where alpr is located to your PATH. In my case `C:\OpenALPR\openalpr_64`
> 5. Use Anaconda Prompt to install the Python bindings (they are in the source code directory). In my case:
> 
> ```
> cd C:\OpenALPR\openalpr-2.3.0\src\bindings\python
> python setup.py install --record files.txt
> ```
> 
> 1. Test your installation in the same prompt:
> 
> ```
> cd C:\OpenALPR\openalpr_64
> python_test.bat
> ```
> 
> Output:
> 
> ```
> Using OpenALPR 2.3.0
> Image size: 497x372
> Processing Time: 22.618999
> Plate #1
>           Plate   Confidence
>   -       THECAR   92.207481
>   -       THEGAR   81.348961
>   -        HECAR   80.229317
>   -       TMECAR   78.159492
>   -       THE0AR   77.702461
>   -       THECAB   77.389000
>   -        THEAR   76.510017
> ```
> 
> Now there is a problem with the unload method of the DLL, but that is another issue: `Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x0000000002C04198>>`. BTW this problem only happen when using alpr.unload().

Do you have to purchase a license key? I followed your steps but i am getting 'Licensing Error'

**Comment by sguerrer** [comment]
> @diogorjs i got the same issue, do you have fixed it? Mine as below:
> 
> > > > alpr = Alpr("us", "D:\openalpr-2.3.0\config\openalpr.conf", "D:\openalpr-2.3
> > > > .0\runtime_data")
> 
> Exception AttributeError: "Alpr instance has no attribute '_is_loaded_func'" in
> <bound method Alpr.**del** of <openalpr.openalpr.Alpr instance at 0x00000000027B
> 9148>> ignored
> Traceback (most recent call last):
> File "", line 1, in
> File "openalpr\openalpr.py", line 58, in **init**
> raise nex
> OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR i
> s properly installed on your system and that the libraries are in the appropriat
> e paths.

Hi, is there a fix already for this?

**Comment by otuwase-hub** [comment]
> Well this is how I got OpenALPR to work on Windows 7/Anaconda 3/python 3.5 x64 :
> 
> 0. You should uninstall any previous version of ALPR
> 1. Download the _binaries_ **and** the _source code_ from https://github.com/openalpr/openalpr/releases
> 2. Unzip the _binaries_ **and** the _source code_ in some directory, for example `C:\OpenALPR`
> 3. Add the directory where alpr is located to your PATH. In my case `C:\OpenALPR\openalpr_64`
> 4. Use Anaconda Prompt to install the Python bindings (they are in the source code directory). In my case:
> 
> ```
> cd C:\OpenALPR\openalpr-2.3.0\src\bindings\python
> python setup.py install --record files.txt
> ```
> 
> 5. Test your installation in the same prompt:
> 
> ```
> cd C:\OpenALPR\openalpr_64
> python_test.bat
> ```
> 
> Output:
> 
> ```
> Using OpenALPR 2.3.0
> Image size: 497x372
> Processing Time: 22.618999
> Plate #1
>           Plate   Confidence
>   -       THECAR   92.207481
>   -       THEGAR   81.348961
>   -        HECAR   80.229317
>   -       TMECAR   78.159492
>   -       THE0AR   77.702461
>   -       THECAB   77.389000
>   -        THEAR   76.510017
> ```
> 
> Now there is a problem with the unload method of the DLL, but that is another issue: `Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x0000000002C04198>>`. BTW this problem only happen when using alpr.unload().

Thank you very much...nothing else worked for me. I think the Anaconda environment is the secret to successfully installing openalpr. I didn't get the alpr.unload() error you were talking about.
Also, for anyone having issues with the config and runtime_data paths, I simply copied the "openalpr.conf" file and runtime_data folder from the openalpr_64 folder in my project directory (I don't know if it was the right thing to do or not).
