### ISSUE TITLE
Can not compile with OpenCV 3.3.1 + CUDA

### ISSUE THREAD

**Issue by psybox** [openalpr/openalpr#739]
Can OpenALPR be used with any of the OpenCV 3.* versions? I have complied OpenCV with CUDA=ON.

`[ 29%] Building CXX object openalpr/CMakeFiles/openalpr.dir/alpr_impl.cpp.o
			/opt/openalpr/src/misc_utilities/prepcharsfortraining.cpp: In function ‘int main(int, const char**)’:
			/opt/openalpr/src/misc_utilities/prepcharsfortraining.cpp:159:42: error: ‘CV_BGR2GRAY’ was not declared in this scope
			       cvtColor(charImgCopy, charImgCopy, CV_BGR2GRAY);
			                                          ^~~~~~~~~~~
			/opt/openalpr/src/misc_utilities/prepcharsfortraining.cpp:165:43: error: ‘CV_RETR_EXTERNAL’ was not declared in this scope
			       findContours(charImgCopy, contours, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_SIMPLE);
			                                           ^~~~~~~~~~~~~~~~
			/opt/openalpr/src/misc_utilities/prepcharsfortraining.cpp:165:43: note: suggested alternative: ‘CV_EXTERN_C’
			       findContours(charImgCopy, contours, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_SIMPLE);
			                                           ^~~~~~~~~~~~~~~~
			                                           CV_EXTERN_C
			/opt/openalpr/src/misc_utilities/prepcharsfortraining.cpp:165:61: error: ‘CV_CHAIN_APPROX_SIMPLE’ was not declared in this scope
			       findContours(charImgCopy, contours, CV_RETR_EXTERNAL, CV_CHAIN_APPROX_SIMPLE);
			                                                             ^~~~~~~~~~~~~~~~~~~~~~
			misc_utilities/CMakeFiles/openalpr-utils-prepcharsfortraining.dir/build.make:62: recipe for target 'misc_utilities/CMakeFiles/openalpr-utils-prepcharsfortraining.dir/prepcharsfortraining.cpp.o' failed
			make[2]: *** [misc_utilities/CMakeFiles/openalpr-utils-prepcharsfortraining.dir/prepcharsfortraining.cpp.o] Error 1
			CMakeFiles/Makefile2:283: recipe for target 'misc_utilities/CMakeFiles/openalpr-utils-prepcharsfortraining.dir/all' failed
			make[1]: *** [misc_utilities/CMakeFiles/openalpr-utils-prepcharsfortraining.dir/all] Error 2
			make[1]: *** Waiting for unfinished jobs....

		[ 30%] Building CXX object openalpr/CMakeFiles/openalpr.dir/detection/detector.cpp.o`

**Comment by xtianhb** [comment]
Have you traced down in openalpr src code and opencv if CUDA=ON define changes that macros scope?

**Comment by onno182** [comment]
The above problem has to do with compiling against OpenCV 3.*.  Either change all the OpenCV version 2 constants for the OpenCV 3 equivalent, or compile against OpenCV 2.

**Comment by navneetk98** [comment]
Can you please give steps for that...Cant find a Opencv version2 and where to change too
