### ISSUE TITLE
Printf not declared while compiling with GPU in detectorcuda.cpp

### ISSUE THREAD

**Issue by corentin87** [openalpr/openalpr#627]
Hi,

On master branch when compiling with GPU
`cmake ../src -DWITH_GPU_DETECTOR=ON`

I get the error:
```
/home/rocketboots/Rocketboots/OpenALPR/openalpr/src/openalpr/detection/detectorcuda.cpp: In constructor ‘alpr::DetectorCUDA::DetectorCUDA(alpr::Config*, alpr::PreWarp*)’:
/home/rocketboots/Rocketboots/OpenALPR/openalpr/src/openalpr/detection/detectorcuda.cpp:38:45: error: ‘printf’ was not declared in this scope
       printf("--(!)Loaded CUDA classifier\n");
                                             ^
/home/rocketboots/Rocketboots/OpenALPR/openalpr/src/openalpr/detection/detectorcuda.cpp:43:83: error: ‘printf’ was not declared in this scope
       printf("--(!)Error loading CPU classifier %s\n", get_detector_file().c_str());
```

It works fine when working on branch v2.3.0.
Between v2.3.0 and master branch, a #include <stdio.h> was removed from detectorcuda.h, causing the error.

**Comment by DhanishVijayan** [comment]
Added the following in detectorcuda.h under #ifdef COMPILE_GPU

#include <stdio.h>

Now compilation is successful
